#CLIENTE#
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Miguel','CH','leugimiii@hotmail.es','1975-05-03','2020-05-03','');
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Mari','CH','leugimiii@hotmail.es','1978-05-03','2020-05-03','');
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Rafa','CH','leugimiii@hotmail.es','1989-05-03','2020-05-03','');
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Pablo','CH','leugimiii@hotmail.es','1997-05-03','2020-05-03','');
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Julia','CH','leugimiii@hotmail.es','1999-05-03','2020-05-03','');
INSERT INTO cliente (nombre,apellido,email,fecha_nacimiento,create_at,foto) VALUES ('Marina','CA','marinamiii@hotmail.es','2008-05-03','2020-05-14','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Andres', 'Guzman', 'profesor@bolsadeideas.com','1989-05-03', '2017-08-01','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('John', 'Doe', 'john.doe@gmail.com','1989-05-03', '2017-08-02','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com','1989-05-03', '2017-08-03','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Jane', 'Doe', 'jane.doe@gmail.com','1989-05-03', '2017-08-04','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com','1989-05-03', '2017-08-05','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com','1989-05-03', '2017-08-06','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Richard', 'Helm', 'richard.helm@gmail.com','1989-05-03', '2017-08-07','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com','1989-05-03', '2017-08-08','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com','1989-05-03', '2017-08-09','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('James', 'Gosling', 'james.gosling@gmail.com','1989-05-03', '2017-08-010','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Bruce', 'Lee', 'bruce.lee@gmail.com','1989-05-03', '2017-08-11','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Johnny', 'Doe', 'johnny.doe@gmail.com','1989-05-03', '2017-08-12','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('John', 'Roe', 'john.roe@gmail.com','1989-05-03', '2017-08-13','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Jane', 'Roe', 'jane.roe@gmail.com','1989-05-03', '2017-08-14','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Richard', 'Doe', 'richard.doe@gmail.com','1989-05-03', '2017-08-15','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Janie', 'Doe', 'janie.doe@gmail.com','1989-05-03', '2017-08-16','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Phillip', 'Webb', 'phillip.webb@gmail.com','1989-05-03', '2017-08-17','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Stephane', 'Nicoll', 'stephane.nicoll@gmail.com','1989-05-03', '2017-08-18','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Sam', 'Brannen', 'sam.brannen@gmail.com','1989-05-03', '2017-08-19','');  
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Juergen', 'Hoeller', 'juergen.Hoeller@gmail.com','1989-05-03', '2017-08-20',''); 
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Janie', 'Roe', 'janie.roe@gmail.com','1989-05-03', '2017-08-21','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('John', 'Smith', 'john.smith@gmail.com','1989-05-03', '2017-08-22','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Joe', 'Bloggs', 'joe.bloggs@gmail.com','1989-05-03', '2017-08-23','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('John', 'Stiles', 'john.stiles@gmail.com','1989-05-03', '2017-08-24','');
INSERT INTO cliente (nombre, apellido, email,fecha_nacimiento, create_at,foto) VALUES('Richard', 'Roe', 'stiles.roe@gmail.com','1989-05-03', '2017-08-25','');
#PRODUCTO#
INSERT INTO producto (nombre, precio, create_at) VALUES('Bicicleta', 150, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Coche', 12000, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Barco', 15000, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Casa', 140000, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Patinete', 70, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Pelota', 10, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Ordenador', 750, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('TV', 1050, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Movil', 150, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Muñeca', 40, NOW());
INSERT INTO producto (nombre, precio, create_at) VALUES('Planta', 30, NOW());
#FACTURA#
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI1', 'ral que cohesiona elementos lingüístis y subtítulos, la  ', NOW(),1);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI2', 'Las ideas que comunica un textlo que se suele denom ', NOW(),1);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI3', 'El nivel microestructural o local está asociado con el concepto .', NOW(),1);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI4', 'Las ideas que comunica un texto están contenida', NOW(),3);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI1', 'ral que cohesiona elementos lingüístis y subtítulos, la  ', NOW(),2);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI2', 'Las ideas que comunica un textlo que se suele denom ', NOW(),2);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI3', 'El nivel microestructural o local está asociado con el concepto .', NOW(),3);
INSERT INTO factura (descripcion, observacion, create_at,client_id) VALUES('WIKI4', 'Las ideas que comunica un texto están contenida', NOW(),2);